import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  users: defineTable({
    email: v.string(),
    password: v.string(),
    first_name: v.string(),
    last_name: v.string(),
    phone_number: v.optional(v.string()),
    driving_licence: v.optional(v.string()),
    role: v.optional(v.string()),
    trust_score: v.optional(v.number()),
    cod_success_count: v.optional(v.number()),
    cod_failure_count: v.optional(v.number()),
    cod_last_failure_reason: v.optional(v.string()),
    cod_disabled: v.optional(v.boolean()),
    cod_disabled_until: v.optional(v.string()),
    created_at: v.optional(v.string()),
    updated_at: v.optional(v.string()),
  }).index("by_email", ["email"]),

  workers: defineTable({
    email: v.string(),
    password: v.string(),
    first_name: v.string(),
    last_name: v.string(),
    phone_number: v.optional(v.string()),
    status: v.optional(v.string()),
    service_type: v.optional(v.string()),
    latitude: v.optional(v.number()),
    longitude: v.optional(v.number()),
    verified: v.optional(v.boolean()),
    status_locked: v.optional(v.boolean()),
    floater_cash: v.optional(v.number()),
    last_cash_collection_at: v.optional(v.string()),
    lock_reason: v.optional(v.string()),
    license_photo: v.optional(v.string()),
    self_photo: v.optional(v.string()),
    docs_submitted_at: v.optional(v.string()),
    pending_balance: v.optional(v.number()),
    last_payout_at: v.optional(v.string()),
    created_at: v.optional(v.string()),
    updated_at: v.optional(v.string()),
  })
    .index("by_email", ["email"])
    .index("by_status", ["status"]),

  fuel_stations: defineTable({
    user_id: v.optional(v.id("users")),
    station_name: v.optional(v.string()),
    email: v.optional(v.string()),
    phone_number: v.optional(v.string()),
    address: v.optional(v.string()),
    latitude: v.optional(v.number()),
    longitude: v.optional(v.number()),
    cod_enabled: v.optional(v.boolean()),
    cod_supported: v.optional(v.boolean()),
    cod_delivery_allowed: v.optional(v.boolean()),
    cod_current_balance: v.optional(v.number()),
    cod_balance_limit: v.optional(v.number()),
    is_verified: v.optional(v.boolean()),
    is_open: v.optional(v.boolean()),
    platform_trust_flag: v.optional(v.boolean()),
    total_earnings: v.optional(v.number()),
    pending_payout: v.optional(v.number()),
    last_stock_update: v.optional(v.string()),
    created_at: v.optional(v.string()),
    updated_at: v.optional(v.string()),
  })
    .index("by_user_id", ["user_id"])
    .index("by_email", ["email"]),

  service_types: defineTable({
    code: v.string(),
    label: v.string(),
    amount: v.number(),
    created_at: v.optional(v.string()),
  }).index("by_code", ["code"]),

  service_requests: defineTable({
    user_id: v.optional(v.id("users")),
    vehicle_number: v.string(),
    driving_licence: v.string(),
    phone_number: v.string(),
    service_type: v.string(),
    amount: v.number(),
    status: v.optional(v.string()),
    fuel_station_id: v.optional(v.id("fuel_stations")),
    payment_method: v.optional(v.string()),
    payment_status: v.optional(v.string()),
    cod_failure_reason: v.optional(v.string()),
    payment_id: v.optional(v.string()),
    payment_details: v.optional(v.string()),
    litres: v.optional(v.number()),
    fuel_price: v.optional(v.number()),
    user_lat: v.optional(v.number()),
    user_lon: v.optional(v.number()),
    assigned_worker: v.optional(v.id("workers")),
    assigned_at: v.optional(v.string()),
    in_progress_at: v.optional(v.string()),
    completed_at: v.optional(v.string()),
    cancelled_at: v.optional(v.string()),
    created_at: v.optional(v.string()),
    rating: v.optional(v.number()),
    review_comment: v.optional(v.string()),
    settlement_id: v.optional(v.id("settlements")),
    completed_delivery_count: v.optional(v.number()),
    distance_km: v.optional(v.number()),
    waiting_time_minutes: v.optional(v.number()),
  })
    .index("by_user_id", ["user_id"])
    .index("by_status", ["status"])
    .index("by_payment_id", ["payment_id"])
    .index("by_assigned_worker", ["assigned_worker"]),

  payments: defineTable({
    service_request_id: v.optional(v.id("service_requests")),
    provider: v.string(),
    provider_payment_id: v.optional(v.string()),
    amount: v.number(),
    currency: v.optional(v.string()),
    status: v.optional(v.string()),
    metadata: v.optional(v.string()),
    created_at: v.optional(v.string()),
    updated_at: v.optional(v.string()),
  })
    .index("by_service_request_id", ["service_request_id"])
    .index("by_provider_payment_id", ["provider_payment_id"])
    .index("by_status", ["status"]),

  settlements: defineTable({
    service_request_id: v.optional(v.id("service_requests")),
    worker_id: v.optional(v.id("workers")),
    fuel_station_id: v.optional(v.id("fuel_stations")),
    settlement_date: v.optional(v.string()),
    customer_amount: v.number(),
    fuel_cost: v.number(),
    delivery_fee: v.number(),
    platform_service_fee: v.number(),
    surge_fee: v.optional(v.number()),
    fuel_station_payout: v.number(),
    worker_payout: v.number(),
    platform_profit: v.number(),
    worker_base_pay: v.optional(v.number()),
    worker_distance_km: v.optional(v.number()),
    worker_distance_pay: v.optional(v.number()),
    worker_surge_bonus: v.optional(v.number()),
    worker_waiting_time_bonus: v.optional(v.number()),
    worker_incentive_bonus: v.optional(v.number()),
    worker_penalty: v.optional(v.number()),
    worker_minimum_guarantee: v.optional(v.number()),
    status: v.optional(v.string()),
    notes: v.optional(v.string()),
    created_at: v.optional(v.string()),
    updated_at: v.optional(v.string()),
  }).index("by_service_request_id", ["service_request_id"]),

  platform_settings: defineTable({
    key: v.string(),
    value_json: v.string(),
    updated_at: v.optional(v.string()),
  }).index("by_key", ["key"]),

  activity_log: defineTable({
    type: v.string(),
    message: v.optional(v.string()),
    entity_type: v.optional(v.string()),
    entity_id: v.optional(v.string()),
    created_at: v.optional(v.string()),
  }).index("by_created_at", ["created_at"]),

  audit_logs: defineTable({
    action: v.string(),
    entity_type: v.string(),
    entity_id: v.string(),
    user_id: v.optional(v.id("users")),
    user_role: v.optional(v.string()),
    old_values: v.optional(v.string()),
    new_values: v.optional(v.string()),
    ip_address: v.optional(v.string()),
    user_agent: v.optional(v.string()),
    description: v.optional(v.string()),
    created_at: v.optional(v.string()),
  }),

  worker_bank_details: defineTable({
    worker_id: v.id("workers"),
    account_holder_name: v.optional(v.string()),
    account_number: v.optional(v.string()),
    ifsc_code: v.optional(v.string()),
    bank_name: v.optional(v.string()),
    is_bank_verified: v.optional(v.number()),
    razorpay_contact_id: v.optional(v.string()),
    razorpay_fund_account_id: v.optional(v.string()),
    rejection_reason: v.optional(v.string()),
    created_at: v.optional(v.string()),
    updated_at: v.optional(v.string()),
  }).index("by_worker_id", ["worker_id"]),

  worker_payouts: defineTable({
    worker_id: v.id("workers"),
    amount: v.number(),
    reference_id: v.optional(v.string()),
    notes: v.optional(v.string()),
    created_at: v.optional(v.string()),
  }).index("by_worker_id", ["worker_id"]),

  payout_logs: defineTable({
    worker_id: v.id("workers"),
    payout_id: v.optional(v.string()),
    amount: v.number(),
    currency: v.optional(v.string()),
    status: v.optional(v.string()),
    error_message: v.optional(v.string()),
    created_at: v.optional(v.string()),
    updated_at: v.optional(v.string()),
  }).index("by_worker_id", ["worker_id"]),

  fuel_station_bank_details: defineTable({
    fuel_station_id: v.id("fuel_stations"),
    account_holder_name: v.string(),
    account_number: v.string(),
    ifsc_code: v.string(),
    bank_name: v.string(),
    razorpay_contact_id: v.optional(v.string()),
    razorpay_fund_account_id: v.optional(v.string()),
    created_at: v.optional(v.string()),
    updated_at: v.optional(v.string()),
  }).index("by_fuel_station_id", ["fuel_station_id"]),

  floating_cash_payments: defineTable({
    worker_id: v.id("workers"),
    amount: v.number(),
    amount_paise: v.number(),
    purpose: v.optional(v.string()),
    razorpay_order_id: v.optional(v.string()),
    razorpay_payment_id: v.optional(v.string()),
    razorpay_signature: v.optional(v.string()),
    status: v.optional(v.string()),
    failure_reason: v.optional(v.string()),
    created_at: v.optional(v.string()),
    updated_at: v.optional(v.string()),
  })
    .index("by_worker_id", ["worker_id"])
    .index("by_razorpay_order_id", ["razorpay_order_id"]),

  password_resets: defineTable({
    user_id: v.optional(v.id("users")),
    account_type: v.optional(v.string()),
    account_id: v.optional(v.string()),
    token: v.string(),
    used: v.optional(v.boolean()),
    created_at: v.optional(v.string()),
    consumed_at: v.optional(v.string()),
  }).index("by_token", ["token"]),

  cod_settings: defineTable({
    singleton_key: v.string(),
    cod_limit: v.optional(v.number()),
    trust_threshold: v.optional(v.number()),
    max_failures: v.optional(v.number()),
    disable_days: v.optional(v.number()),
    updated_at: v.optional(v.string()),
  }).index("by_singleton_key", ["singleton_key"]),

  service_prices: defineTable({
    service_type: v.string(),
    amount: v.number(),
    updated_at: v.optional(v.string()),
  }).index("by_service_type", ["service_type"]),

  worker_station_cache: defineTable({
    worker_id: v.id("workers"),
    service_request_id: v.id("service_requests"),
    fuel_station_id: v.id("fuel_stations"),
    assigned_at: v.optional(v.string()),
    worker_lat: v.optional(v.number()),
    worker_lng: v.optional(v.number()),
    distance_km: v.optional(v.number()),
    is_valid: v.optional(v.boolean()),
    invalidated_at: v.optional(v.string()),
  }),

  fuel_station_assignments: defineTable({
    service_request_id: v.id("service_requests"),
    worker_id: v.id("workers"),
    fuel_station_id: v.id("fuel_stations"),
    fuel_type: v.string(),
    litres: v.number(),
    distance_km: v.number(),
    is_cod: v.optional(v.boolean()),
    supports_cod: v.optional(v.boolean()),
    assigned_at: v.optional(v.string()),
    picked_up_at: v.optional(v.string()),
    status: v.optional(v.string()),
    rejection_reason: v.optional(v.string()),
    reassignment_count: v.optional(v.number()),
    created_at: v.optional(v.string()),
    updated_at: v.optional(v.string()),
  }),

  fuel_station_stock: defineTable({
    fuel_station_id: v.id("fuel_stations"),
    fuel_type: v.string(),
    stock_litres: v.optional(v.number()),
    last_refilled_at: v.optional(v.string()),
    created_at: v.optional(v.string()),
    updated_at: v.optional(v.string()),
  }),

  fuel_station_ledger: defineTable({
    fuel_station_id: v.id("fuel_stations"),
    settlement_id: v.optional(v.id("settlements")),
    transaction_type: v.string(),
    amount: v.number(),
    description: v.optional(v.string()),
    running_balance: v.optional(v.number()),
    status: v.optional(v.string()),
    reference_id: v.optional(v.string()),
    created_at: v.optional(v.string()),
    updated_at: v.optional(v.string()),
  }),

  cod_settlements: defineTable({
    service_request_id: v.id("service_requests"),
    fuel_station_id: v.id("fuel_stations"),
    worker_id: v.id("workers"),
    customer_paid_amount: v.number(),
    fuel_cost: v.number(),
    fuel_station_payout: v.number(),
    platform_fee: v.optional(v.number()),
    collection_method: v.optional(v.string()),
    payment_status: v.optional(v.string()),
    collected_at: v.optional(v.string()),
    settled_at: v.optional(v.string()),
    notes: v.optional(v.string()),
    created_at: v.optional(v.string()),
    updated_at: v.optional(v.string()),
  }),

  connectivity_reports: defineTable({
    lat: v.number(),
    lng: v.number(),
    severity: v.string(),
    effective_type: v.optional(v.string()),
    downlink: v.optional(v.number()),
    rtt: v.optional(v.number()),
    failures: v.optional(v.number()),
    offline: v.optional(v.number()),
    reported_at: v.string(),
  }),
});

